config/routes.rb
Rails.application.routes.draw do
  resources :fdsafsdfs
  resources :asdfs

  resources :posts

  root to: 'posts#index'

end

app/models/asdf.rb
class Asdf < ActiveRecord::Base
end

app/models/fdsafsdf.rb
class Fdsafsdf < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/asdfs_controller.rb
class AsdfsController < ApplicationController
  before_action :set_asdf, only: [:show, :edit, :update, :destroy]

  # GET /asdfs
  # GET /asdfs.json
  def index
    @asdfs = Asdf.all
  end

  # GET /asdfs/1
  # GET /asdfs/1.json
  def show
  end

  # GET /asdfs/new
  def new
    @asdf = Asdf.new
  end

  # GET /asdfs/1/edit
  def edit
  end

  # POST /asdfs
  # POST /asdfs.json
  def create
    @asdf = Asdf.new(asdf_params)

    respond_to do |format|
      if @asdf.save
        format.html { redirect_to @asdf, notice: 'Asdf was successfully created.' }
        format.json { render :show, status: :created, location: @asdf }
      else
        format.html { render :new }
        format.json { render json: @asdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asdfs/1
  # PATCH/PUT /asdfs/1.json
  def update
    respond_to do |format|
      if @asdf.update(asdf_params)
        format.html { redirect_to @asdf, notice: 'Asdf was successfully updated.' }
        format.json { render :show, status: :ok, location: @asdf }
      else
        format.html { render :edit }
        format.json { render json: @asdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asdfs/1
  # DELETE /asdfs/1.json
  def destroy
    @asdf.destroy
    respond_to do |format|
      format.html { redirect_to asdfs_url, notice: 'Asdf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asdf
      @asdf = Asdf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asdf_params
      params.require(:asdf).permit(:asdf)
    end
end

app/controllers/fdsafsdfs_controller.rb
class FdsafsdfsController < ApplicationController
  before_action :set_fdsafsdf, only: [:show, :edit, :update, :destroy]

  # GET /fdsafsdfs
  # GET /fdsafsdfs.json
  def index
    @fdsafsdfs = Fdsafsdf.all
  end

  # GET /fdsafsdfs/1
  # GET /fdsafsdfs/1.json
  def show
  end

  # GET /fdsafsdfs/new
  def new
    @fdsafsdf = Fdsafsdf.new
  end

  # GET /fdsafsdfs/1/edit
  def edit
  end

  # POST /fdsafsdfs
  # POST /fdsafsdfs.json
  def create
    @fdsafsdf = Fdsafsdf.new(fdsafsdf_params)

    respond_to do |format|
      if @fdsafsdf.save
        format.html { redirect_to @fdsafsdf, notice: 'Fdsafsdf was successfully created.' }
        format.json { render :show, status: :created, location: @fdsafsdf }
      else
        format.html { render :new }
        format.json { render json: @fdsafsdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fdsafsdfs/1
  # PATCH/PUT /fdsafsdfs/1.json
  def update
    respond_to do |format|
      if @fdsafsdf.update(fdsafsdf_params)
        format.html { redirect_to @fdsafsdf, notice: 'Fdsafsdf was successfully updated.' }
        format.json { render :show, status: :ok, location: @fdsafsdf }
      else
        format.html { render :edit }
        format.json { render json: @fdsafsdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fdsafsdfs/1
  # DELETE /fdsafsdfs/1.json
  def destroy
    @fdsafsdf.destroy
    respond_to do |format|
      format.html { redirect_to fdsafsdfs_url, notice: 'Fdsafsdf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fdsafsdf
      @fdsafsdf = Fdsafsdf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fdsafsdf_params
      params[:fdsafsdf]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asdfs_helper.rb
module AsdfsHelper
end

app/helpers/fdsafsdfs_helper.rb
module FdsafsdfsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/asdfs/_form.html.erb
<%= form_for(@asdf) do |f| %>
  <% if @asdf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asdf.errors.count, "error") %> prohibited this asdf from being saved:</h2>

      <ul>
      <% @asdf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asdf %><br>
    <%= f.text_field :asdf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asdfs/edit.html.erb
<h1>Editing asdf</h1>

<%= render 'form' %>

<%= link_to 'Show', @asdf %> |
<%= link_to 'Back', asdfs_path %>

app/views/asdfs/index.html.erb
<h1>Listing asdfs</h1>

<table>
  <thead>
    <tr>
      <th>Asdf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asdfs.each do |asdf| %>
      <tr>
        <td><%= asdf.asdf %></td>
        <td><%= link_to 'Show', asdf %></td>
        <td><%= link_to 'Edit', edit_asdf_path(asdf) %></td>
        <td><%= link_to 'Destroy', asdf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asdf', new_asdf_path %>

app/views/asdfs/new.html.erb
<h1>New asdf</h1>

<%= render 'form' %>

<%= link_to 'Back', asdfs_path %>

app/views/asdfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asdf:</strong>
  <%= @asdf.asdf %>
</p>

<%= link_to 'Edit', edit_asdf_path(@asdf) %> |
<%= link_to 'Back', asdfs_path %>

app/views/fdsafsdfs/_form.html.erb
<%= form_for(@fdsafsdf) do |f| %>
  <% if @fdsafsdf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fdsafsdf.errors.count, "error") %> prohibited this fdsafsdf from being saved:</h2>

      <ul>
      <% @fdsafsdf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fdsafsdfs/edit.html.erb
<h1>Editing fdsafsdf</h1>

<%= render 'form' %>

<%= link_to 'Show', @fdsafsdf %> |
<%= link_to 'Back', fdsafsdfs_path %>

app/views/fdsafsdfs/index.html.erb
<h1>Listing fdsafsdfs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fdsafsdfs.each do |fdsafsdf| %>
      <tr>
        <td><%= link_to 'Show', fdsafsdf %></td>
        <td><%= link_to 'Edit', edit_fdsafsdf_path(fdsafsdf) %></td>
        <td><%= link_to 'Destroy', fdsafsdf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fdsafsdf', new_fdsafsdf_path %>

app/views/fdsafsdfs/new.html.erb
<h1>New fdsafsdf</h1>

<%= render 'form' %>

<%= link_to 'Back', fdsafsdfs_path %>

app/views/fdsafsdfs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fdsafsdf_path(@fdsafsdf) %> |
<%= link_to 'Back', fdsafsdfs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

These are posts from awesome users like you!<br />

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.author %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>